In [2]:
from download_zip import download

url = "https://www.skm.pkp.pl/gtfs-mi-kpd.zip"
filename = "gtfs-mi-kpd.zip"

download(url, filename)

import gtfs_kit as gk

feed = gk.read_feed(filename, dist_units='km')

feed.describe()

File was created less than 24h ago, using cached version

,indicator,value
0,agencies,[PKP Szybka Kolej Miejska w Trójmieście Sp. z ...
1,timezone,Europe/Warsaw
2,start_date,20231208
3,end_date,20240309
4,num_routes,1162
5,num_trips,1162
6,num_stops,35
7,num_shapes,1162
8,sample_date,20231214
9,num_routes_active_on_sample_date,228
10,num_trips_active_on_sample_date,228
11,num_stops_active_on_sample_date,35

In [32]:
feed.stops

,stop_id,stop_name,stop_lat,stop_lon,wheelchair_boarding
0,5256,Lębork,54.533686,17.750430,0
1,5413,Godętowo,54.582047,17.864818,0
2,5421,Bożepole Wielkie,54.568872,17.967674,0
3,5439,Strzebielino Morskie,54.562847,18.029762,0
4,5447,Luzino,54.567163,18.103513,0
5,5900,Gdynia Główna,54.520191,18.531351,1
6,5918,Gdynia Redłowo,54.491662,18.538313,0
7,5926,Gdynia Wzgórze Św.Maksym.,54.507969,18.535571,1
8,5934,Gdynia Orłowo,54.476721,18.549024,0
9,5942,Sopot,54.440067,18.562457,1
10,5959,Sopot Kamienny Potok,54.457764,18.553583,0
11,5967,Sopot Wyścigi,54.430836,18.565351,1
12,6031,Gdynia Chylonia,54.545692,18.463601,0
13,6049,Gdynia Stocznia–UMorski,54.525634,18.519033,0
14,6056,Gdynia Grabówek,54.534573,18.495341,0
15,6064,Gdynia Leszczynki,54.541423,18.478242,0
16,6080,Rumia Janowo,54.558921,18.405782,0
17,6098,Rumia,54.569062,18.386524,0
18,6106,Reda,54.595332,18.352881,0
19,6114,Reda Pieleszewo,54.602733,18.317673,0
20,6304,Wejherowo,54.605852,18.229546,0
21,6312,Wejherowo Śmiechowo,54.601991,18.274150,0
22,6320,Wejherowo Nanice,54.603718,18.247765,0
23,6593,Gościcino Wejherowskie,54.604926,18.161033,0
24,7500,Gdańsk Główny,54.356592,18.644349,1
25,7518,Gdańsk Stocznia,54.364462,18.641972,0
26,7526,Gdańsk Politechnika,54.374245,18.627137,1
27,7534,Gdańsk Wrzeszcz,54.382173,18.605076,1
28,7559,Gdańsk Zaspa,54.389906,18.591316,1
29,7567,Gdańsk Przymorze-Uniwer.,54.400653,18.576650,1
30,7617,Gdańsk Żabianka - AWFiS,54.420662,18.568536,1
31,178829,Gdynia Cisowa,54.550083,18.445457,1
32,251577,Gdańsk Oliwa,54.410554,18.571724,1
33,254531,Lębork Mosty,54.550715,17.793863,0
34,258458,Gdańsk Śródmieście,54.346091,18.644662,1

In [31]:
from datetime import datetime

def convert_datetime(rows):
    date = rows.date
    time = rows.arrival_time

    h, m, s = rows.arrival_time.split(":")
    if h == "24":
        h = "00"
        time = f"{h}:{m}:{s}"

    return datetime.strptime(f"{date} {time}", "%Y%m%d %H:%M:%S")

now = datetime.now()
next_arrivals = gk.stops.build_stop_timetable(feed, "7567", [now.strftime("%Y%m%d")]).copy()
next_arrivals["arrival_datetime"] = next_arrivals[["arrival_time", "date"]].apply(convert_datetime, axis=1)
next_arrivals = next_arrivals[["trip_headsign", "arrival_datetime"]]
next_arrivals = next_arrivals[next_arrivals['arrival_datetime'] > now]
next_arrivals = next_arrivals.sort_values("arrival_datetime")
next_arrivals.head(10)

            trip_headsign    arrival_datetime
11002  Gdańsk Śródmieście 2024-01-13 11:49:06
15863           Wejherowo 2024-01-13 11:54:30
10768  Gdańsk Śródmieście 2024-01-13 12:00:06
19006     Gdynia Chylonia 2024-01-13 12:04:30
11457  Gdańsk Śródmieście 2024-01-13 12:09:06
25102           Wejherowo 2024-01-13 12:14:30
9900   Gdańsk Śródmieście 2024-01-13 12:19:06
9933      Gdynia Chylonia 2024-01-13 12:24:30
11429  Gdańsk Śródmieście 2024-01-13 12:29:06
15632           Wejherowo 2024-01-13 12:34:30